# Generated by Django 5.2.6 on 2025-09-27 17:35

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('jobs', '0002_create_search_index'),
#     ]

#     operations = [
#     ]

# jobs/migrations/0002_enable_btree_gin.py

from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # Ensure this dependency points to your last migration in the jobs app (which should be 0001)
        ('jobs', '0001_enable_btree_gin'),
    ]

    operations = [
        # This operation enables the Btree_Gin extension needed for GIN indexing on text fields
        BtreeGinExtension(),
    ]