version: "3.8"
services:
  web:
    build: .
    command: gunicorn jobboard.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
      - redis
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: jobboard
      POSTGRES_USER: jobboard_user
      POSTGRES_PASSWORD: changeme
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A jobboard worker -l info
    env_file:
      - .env
    depends_on:
      - web
      - rabbitmq
      - redis
volumes:
  postgres_data:
