version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/geoffy1/project-nexus:latest
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    environment:
      - PORT=8000
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
